clc;
clear;
X = double(imread('x1.bmp'));
Y = double(imread('y6.bmp'));
[m, n] = size(X);
[p, ~] = size(Y);
m = m+1;
X(m, :) = ones(1, n);
V = rand(p, m);
Xx = pseudoinverse(X);
Z = eye(m) - X * Xx;
A = Y * Xx + V * Z';
B = A * X;
l = min(B(:));
r = max(B(:));
B = ((B - l) / (r - l) * 255);
C = uint8(B);
imshow(uint8(B));
imwrite(uint8(A * X), 'out.bmp');