/* BEGIN USERS */
CREATE TABLE "WITALIA"."USERS" (
    "ID" NUMBER(10,0) NOT NULL ENABLE,
    "USERNAME" VARCHAR2(100) NOT NULL ENABLE,
    "PASSHASH" VARCHAR2(256) NOT NULL ENABLE,
    "SALT" VARCHAR2(100) NOT NULL ENABLE,
    PRIMARY KEY ("ID")
);


CREATE SEQUENCE  "WITALIA"."ID_SEQ"
MINVALUE 1 MAXVALUE 9999999999999999999999999999
INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  CYCLE;

CREATE OR REPLACE TRIGGER "WITALIA"."USERID_TRIG"
BEFORE INSERT ON users
FOR EACH ROW

    BEGIN
        SELECT id_seq.NEXTVAL
        INTO   :new.id
        FROM   dual;
    END;
/
/* END USERS */

/* BEGIN ROLES */
CREATE TABLE "WITALIA"."ROLES" (
    "ID" NUMBER NOT NULL ENABLE,
    "ROLE" VARCHAR2(20) DEFAULT USER NOT NULL ENABLE
);

CREATE SEQUENCE  "WITALIA"."RID_SEQ"
MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1
START WITH 1 CACHE 20 ORDER  CYCLE;

CREATE OR REPLACE TRIGGER "WITALIA"."ROLES_ID_TRIG"
BEFORE INSERT ON ROLES
FOR EACH ROW

    BEGIN
        SELECT rid_seq.NEXTVAL
        INTO   :new.id
        FROM   dual;
    END;
/
/* END ROLES */

/* BEGIN ORDERS */
CREATE TABLE WITALIA.ORDERS
(
    ID INT PRIMARY KEY NOT NULL,
    PRODUCT_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    AMOUNT INT NOT NULL
);
ALTER TABLE WITALIA.ORDERS
ADD CONSTRAINT unique_ID UNIQUE (ID);

CREATE SEQUENCE  "WITALIA"."OID_SEQ"
MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1
START WITH 1 CACHE 20 ORDER  CYCLE;

CREATE OR REPLACE TRIGGER "WITALIA"."ORDERS_ID_TRIG"
BEFORE INSERT ON ORDERS
FOR EACH ROW

    BEGIN
        SELECT oid_seq.NEXTVAL
        INTO   :new.id
        FROM   dual;
    END;
/
/* END ORDERS */

/* BEGIN PRODUCTS */
CREATE TABLE WITALIA.PRODUCTS
(
    ID INT PRIMARY KEY NOT NULL,
    PRTYPE VARCHAR2(4000) NOT NULL,
    NAME VARCHAR2(4000) NOT NULL,
    PRICE INT NOT NULL,
    DESCR VARCHAR2(4000) NOT NULL
);
ALTER TABLE WITALIA.PRODUCTS
ADD CONSTRAINT unique_ID UNIQUE (ID);

CREATE SEQUENCE  "WITALIA"."PID_SEQ"
MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1
START WITH 1 CACHE 20 ORDER  CYCLE;

CREATE OR REPLACE TRIGGER "WITALIA"."PRODUCT_ID_TRIG"
BEFORE INSERT ON PRODUCTS
FOR EACH ROW

    BEGIN
        SELECT pid_seq.NEXTVAL
        INTO   :new.id
        FROM   dual;
    END;
/
/* END PRODUCTS */