create database RENT_A_CAR;

CREATE TABLE rent_a_car.USERS
(
  ID INT PRIMARY KEY NOT NULL,
  `_NAME` VARCHAR(100) NOT NULL,
  `_PASS` VARCHAR(200) NOT NULL
);
ALTER TABLE rent_a_car.USERS ADD CONSTRAINT unique_ID UNIQUE (ID);

CREATE TABLE rent_a_car.ROLES
(
  ID INT PRIMARY KEY NOT NULL,
  USER_ID INT NOT NULL,
  ROLE VARCHAR(50) NOT NULL
);
ALTER TABLE rent_a_car.ROLES ADD CONSTRAINT unique_ID UNIQUE (ID);

ALTER TABLE rent_a_car.roles
ADD FOREIGN KEY (USER_ID) REFERENCES users (ID);

CREATE TABLE rent_a_car.CARS
(
  ID INT PRIMARY KEY NOT NULL,
  `_NAME` VARCHAR(100) NOT NULL,
  SEATS INT NOT NULL,
  PRICE DOUBLE NOT NULL
);
ALTER TABLE rent_a_car.CARS ADD CONSTRAINT unique_ID UNIQUE (ID);

CREATE TABLE rent_a_car.ORDERS
(
  ID INT PRIMARY KEY NOT NULL,
  USER_ID INT NOT NULL,
  CAR_ID INT NOT NULL,
  PASSPORT_NO VARCHAR(10) NOT NULL,
  `_LENGTH` INT NOT NULL,
  REFUSAL VARCHAR(500) NOT NULL,
  PAID BOOLEAN NOT NULL
);
ALTER TABLE rent_a_car.ORDERS ADD CONSTRAINT unique_ID UNIQUE (ID);

ALTER TABLE rent_a_car.orders
ADD FOREIGN KEY (USER_ID) REFERENCES users (ID);
ALTER TABLE rent_a_car.orders
ADD FOREIGN KEY (CAR_ID) REFERENCES cars (ID);

CREATE TABLE rent_a_car.BILLS
(
  ORDER_ID INT NOT NULL,
  AMOUNT INT NOT NULL,
  COMMENT VARCHAR(500) NOT NULL
);

ALTER TABLE rent_a_car.bills
ADD FOREIGN KEY (ORDER_ID) REFERENCES orders (ID);