CREATE DATABASE STOCK;
USE STOCK;
CREATE TABLE CATEGORIES (
  ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  NAME VARCHAR(32)
);
CREATE TABLE PRODUCTS (
  ID_CAT INTEGER NOT NULL ,
  ID_PROD INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  NAME VARCHAR(32) NOT NULL ,
  COUNT INTEGER NOT NULL ,
  PRICE DOUBLE NOT NULL ,
  FAT INTEGER NOT NULL
);
ALTER TABLE stock.products
ADD FOREIGN KEY (ID_CAT) REFERENCES categories (ID_CAT);