source 'https://rubygems.org'

# Rails Support Lib Classes
gem 'activesupport'

# Rails Internationalization
gem 'i18n'

# Cramp Framework
gem 'cramp'

# Ruby Redis Driver
gem 'redis'

# JSON support
gem 'json'

# Async webserver for running a cramp application
gem 'thin'

# Rack based routing
gem 'http_router'

# Collection of async-proof rack middlewares - https://github.com/rkh/async-rack.git
gem 'async-rack'